[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd server && npm install && cd .. && npm run build:production"

[deploy]
startCommand = "node dist/server/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.environment]
NODE_ENV = "production"
PORT = "3001"

[[services]]
name = "crypto-flipz"
source = "."

[services.crypto-flipz.env]
PORT = { default = "3001" }
NODE_ENV = { default = "production" }
DATABASE_PATH = "/app/games.db"

[[services]]
name = "crypto-flipz-frontend" 
source = "."

[services.crypto-flipz-frontend.env]
VITE_API_URL = { reference = "crypto-flipz-backend.url" }
VITE_WS_URL = { reference = "crypto-flipz-backend.url" } 