[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "crypto-flipz-backend"
source = "server"

[services.crypto-flipz-backend.env]
PORT = { default = "3001" }
NODE_ENV = { default = "production" }

[[services]]
name = "crypto-flipz-frontend" 
source = "."

[services.crypto-flipz-frontend.env]
VITE_API_URL = { reference = "crypto-flipz-backend.url" }
VITE_WS_URL = { reference = "crypto-flipz-backend.url" } 